spring:
  config:
    import: "aws-secretsmanager:bcar-prod"
dynamodb:
  cars-table: bcar-prod-cars
batch:
  detail-shards: 16
  jobs:
    collect-detail:
      queue: bcar-prod-detail-queue
      definition: bcar-prod-detail-job
